version: '3.8'

services:
  # Flutter web app
  web:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "2080:80"
    restart: unless-stopped
    networks:
      - dolg-network

networks:
  dolg-network:
    driver: bridge

volumes:
  postgres_data: 
