name: lawnmate_employee
description: LawnMate Employee App for managing appointments, customers, and more.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  http: ^1.1.0
  provider: ^6.0.5
  flutter_secure_storage: ^10.0.0-beta.4
  intl: ^0.19.0
  flutter_dotenv: ^5.1.0
  go_router: ^14.8.1
  json_annotation: ^4.8.1
  flutter_svg: ^2.0.7
  cached_network_image: ^3.3.0
  image_picker: ^1.0.4
  file_picker: ^9.2.0
  url_launcher: ^6.2.1
  shared_preferences: ^2.2.2
  flutter_localizations:
    sdk: flutter
  window_size:
    git:
      url: https://github.com/google/flutter-desktop-embedding.git
      path: plugins/window_size
  bitsdojo_window: ^0.1.6
  window_manager: ^0.4.3
  flutter_acrylic: ^1.1.3
  desktop_drop: ^0.5.0
  path_provider: ^2.1.2
  path_provider_windows: ^2.2.2
  logging: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.6
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/